### ISSUE TITLE
DaaS Switch - SPECS

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#100]
The DAPPMANAGER could be able to modify the docker-composes automatically to change the network settings for the new macvlan network. Also, it should restore all the docker-composes from their manifests, when the DaaS mode is deactivated

The ADMIN should offer a switch to active / deactivate the mode and allow to specify the network IP range and possible IPs already allocated.

**Comment by vdo** [comment]
This is a complex feature, since we can have a very different range of configurations. Also, not only docker-compose files need to be modified, also WAMP and BIND need to be customized.

I see this more like a build script which accepts parameters to build a custom dappnode distribution, plus bootstrap scripts which need to be run on the host, than a DAPPMANAGER switch.

**Comment by dapplion** [comment]
Closing as it will not be pursued at the moment
