### ISSUE TITLE
Resolve internal subdomains

### ISSUE THREAD

**Issue by derfredy** [dappnode/DAppNode#135]
Parent package subdomain resolves very well to container ip.

> ping mypackage.public.dappnode
PING mypackage.public.dappnode (172.33.0.3) 56(84) bytes of data.
64 bytes from 172.33.0.3 (172.33.0.3): icmp_seq=1 ttl=63 time=1.25 ms

But this one does not work:

> ping rpc.mypackage.public.dappnode
ping: rpc.mypackage.public.dappnode: Nombre o servicio desconocido

Possible solutions:
* It would be nice that those subdomains resolve to a given container ip. 
key : value pairs in manifest would help for this purpose.
* The easiest but not so flexible solution is to resolve *.package.public.dappnode against the same package IP.

With the first approach, same package could reach different nodes. This could be very usefull for Tendermint or substrate derived nodes where with just one explorer package we could explore blocks in many different networks.

**Comment by dapplion** [comment]
@eduadiez How hard would this be to implement?

**Comment by eduadiez** [comment]
I think this isn't needed since now we've multi-service functionality. 

In case you want to use subdomains, you can have several services on the same package. On the other hand, if you want to use the same IP, it doesn't make sense to use a subdomain because you can use the package domain directly.
