### ISSUE TITLE
Change the order of IP addresses in the VPN config

### ISSUE THREAD

**Issue by wendydv1989** [dappnode/DAppNode#182]
Some consumer routers do not support NAT loopback connections. In the DappNode VPN config file, both an internal and external hostname / ip address are set. If we change the order (first internal ip address, then dyndns) user without Loopback will have no issues.

**Comment by dapplion** [comment]
Thanks for the proposal @wendydv1989 :heart:

@eduadiez What do you think of this?

**Comment by eduadiez** [comment]
Thanks for the suggestion!

In any case after a failure to connect to the first remote due to the lack of NAT loopback on the router it should try with the second remote (internal IP), so people without NAT Loopback shouldn't have any problem to connect more than wait more time than expected. If we change the order all the users will suffer this extra time of waiting every time that they try to connect from an external network. So the current order try to minimize the waiting to connect for all the users in general.
