### ISSUE TITLE
Http failure response for http://prysm-pyrmont.dappnode/api/v2/validator/wallet/keystores/import  400 bad request - Prysm Pyrmont UI on Dappnode

### ISSUE THREAD

**Issue by jonjomatic** [dappnode/DAppNode#221]
Hi folks 

Getting the following error or bug on Prysm Pyrmont UI Dappnode when I have entered a wallet password.  Nothing I can think of is working

![image](https://user-images.githubusercontent.com/75774679/101729893-05e11380-3af4-11eb-999c-6c39abd3ce6b.png)

Have tried big passwords, uninstalling prysm pyrmont and reinstalling, restaring geth and goerli geth, and making sure I only upload the keystore.json file (I have previously uploaded the wrong one, the deposit data)

But still consistently getting this error.

Concerned I may have to drop dappnode but I kind of need to do the eth2 staking through a GUI as I can't code and am not familiar with linux CLI

Anyone have any ideas?

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **wifi.dnp.dappnode.eth**: 0.2.5
- **ipfs.dnp.dappnode.eth**: 0.2.12
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-4-amd64
- **Disk usage**: 339731913114

**Comment by ruvenni** [comment]
This issue is already reported to Prysm Team [here](https://github.com/prysmaticlabs/prysm-web-ui/issues/110) and it's not something depending on DAppNode.

Things you can do:

- Set the password as stated [here](https://medium.com/dappnode/step-by-step-staking-for-dappnode-users-92fdf7db0d0d) in our guide
- Be careful to only upload deposit.json alike file to the Prysm UI as shown [here](https://forum.dappnode.io/t/dappnode-and-pyrmont-errors/472/18?u=ruvenni)

**Comment by jonjomatic** [comment]
Overall seems to be solved - Tried all of the above including automatic updates and left the system for a couple of days.  Tried setting up Prysm again and it worked without any errors this time. Thank you.
