### ISSUE TITLE
DAppNode unreachable

### ISSUE THREAD

**Issue by rylo2020** [dappnode/DAppNode#224]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.14
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **Disk usage**: 347140731699

----

my access to my dappnode only last about 30 minutes . the orange light on the mini dappnode goes solid ipfs does not resolve and dappnode is not reachable. i have not been able to resync geth because the freezing has me constantly restarting

**Comment by rylo2020** [comment]
for about a week it ran great now its constantly running into the same issue

**Comment by ruvenni** [comment]
Hi @rylo2020 
Do you know if the instability could be triggered because of some change was applied to the DAppNode? I mean did you do something like adding a new DApp or starting a new full node client that may be the root problem?

Anyway you can try to update from http://my.dappnode/#/system/auto-updates 1 and see if that solves it. Also if you know hot to connect to the DAppNode with ssh you may perform a restore by launching `wget -qO - https://installer.dappnode.io | sudo UPDATE=true bash` from the terminal.

If Get is not working, have a look at the logs in case they have something relevant to show.
