### ISSUE TITLE
Add Wireguard as VPN

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DAppNode#246]
It would be great to add [Wireguard](https://www.wireguard.com/) as a VPN option and also add a standard UI to manage the users like https://github.com/subspacecloud/subspace.

**Comment by lukagulin** [comment]
I have been researching this, and maybe this project could be better: https://github.com/linuxserver/docker-wireguard

It doesn't have UI, but it seems to me that it could be easily integrated in DAppNode.

**Comment by dapplion** [comment]
The costs of maintaining a custom UI are very high, just something to keep in mind hahaha

**Comment by lukagulin** [comment]
Wireguard package for DAppNode has gone through these steps:

- Fork from https://github.com/linuxserver/docker-wireguard
- Added simple API to fetch configuration files and configuration QR codes
- Made sure that few different versions of the Wireguard are first tried to install before giving up
- Limited testing

Things left to be done:
- More testing
- Adding simple dappmanager conditional UI which would set ENV variable which represents list of devices. That is also only configuration setting that needs to be done

I underlined testing twice in previous parts because it is especially critical for package like this. Since Wireguard lives in the kernel, it needs to be built there and that is where Docker's isolations ends. I think that pretty good job is done exploring every different case, but still we need to be sure that it would actually build on all kinds of machines.

**Comment by dapplion** [comment]
Wireguard has been integrated in the DAPPMANAGER with https://github.com/dappnode/DNP_DAPPMANAGER/pull/637. The UI is hidden but accessible at http://my.dappnode/#/wireguard. Now:

- Keep testing the entire task
- Once ready: release Wireguard package + make the UI more visible

**Comment by dapplion** [comment]
@3alpha @eduadiez Some considerations about Wireguard (vs OpenVPN)

- Wireguard does not support multiple endpoints, that's an issue for NAT loopback
- If wireguard is installed directly on the host on installation our life would be much easier. How to do that?

**Comment by 3alpha** [comment]
My proposal for installation on host is like this. First we have to acknowledge three rough types of situations

- Already installed DAppNodes. This is the "riskiest" as everything is done through docker and things can fail
- Installer script: We can add Wireguard in prerequisites script and on most normal machines it works fine. Only issues I encountered there were VPS machines because they use custom kernels. But DAppNodes should not be run on VPSes anyway :)
- ISO image, there we control everything and should be risk free.

Since Wireguard is quickly getting adopted and from Debian Bullseye it will be standard part of Debian I expect any issues with it, if any, will get solved as time goes on.

**Comment by dapplion** [comment]
This is already implemented and will land on the next DAppNode version. Closing for now
