### ISSUE TITLE
Including Fail2Ban in DAppnode

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#247]
It would be interesting to include some tool like this in dappnode, to the users can improve the defences against brute force attacks and making the installation more user-friendly, using a UI to do it or doing it automatically in the installation, instead of changing /etc/fail2ban/jail.conf file (for example).

**Comment by Zer0Wei** [comment]
+1 on this

**Comment by dapplion** [comment]
@3alpha Why closing? Leave a note with reasoning please

**Comment by 3alpha** [comment]
On one hand it is very hard to integrate in DAppNode properly because it goes to the core of the system and controlling it on frontend will be sketchy. On the other hand it has very limited usability for non-advanced users since majority of things it protects from are used by users bit more familiar with the command line who can set it up very quickly if they wanted to.
