### ISSUE TITLE
Docker uses public IP range

### ISSUE THREAD

**Issue by jbacker** [dappnode/DAppNode#283]
It appears as if a fresh installation of dappnode (using ISO) uses a (humongous) IP range of 172.33.0.0/16 for Docker, e.g. Geth gets 172.33.0.2.

This isn't one of the private RFC1918 ranges that can be used for these purposes (and in fact, the IP range is overlapping with an actual live ISP). We can't just grab any IP range for this, please stick to private address space.

For what it's worth, it appears as if there is a (humongous) 172.17.0.0/16 range on the system as well which doesn't appear to be used.

**Comment by 3alpha** [comment]
Good catch, this is an issue we are aware of and are actively working on it. Some packages require IPs to be hardcoded and because of that it is not just matter of changing IPs in the next release. We need to make sure that update goes smoothly and test it thoroughly because any gremlin here would break DAppNodes badly.

**Comment by lodotek** [comment]
Any update here? Is there a branch yet for any work started that relates to this?

**Comment by 3alpha** [comment]
Opened issue at: https://github.com/dappnode/DNP_DAPPMANAGER/issues/951
