### ISSUE TITLE
Road to eth2 multiclients in DAppNode ⧫

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#329]
DAppNode supports diversification of clients in the eth2 (POS consensus layer) for the good of the network. However we are not able to support any other client but Prysm since it's the only one that features a UI. Note that the value proposition of DAppNode is to reduce the technical complexity of running nodes and other DApps, which means not having to interact with a CLI.

We are exploring different paths to integrate a UI into the usage flow of other clients

**A: Add a UI to the client**

Like Prysm did, embed a UI in the validator client of that implementation with a supporting backend API to perform keymanagment. The cost of this route is very high and isn't likely to be completed anytime soon.

- Prysm: :heavy_check_mark: Already has a UI + backend
- Lighthouse: :hourglass_flowing_sand: UI in the works, unknown ETA. Backend already implemented
- Teku: :x: Not actively pursuing this
- Nimbus: :x: Interested in developing one potentially
- Lodestar: :x: Not actively pursuing this

**B: Add only UI backend to the client**

Given that there's already a functional UI developed, clients could implement just the keymanager UI backend to their signer binaries (either validator client or remote signer) and achieve the same result. This option should be far cheaper to develop, since it does not involve any front-end work: just exposing existing functionality through an HTTP API.

This PR *Add local validator manager API #151* https://github.com/ethereum/eth2.0-APIs/pull/151 wants to signal the minimal routes to develop to client teams. Note that no client supports any version of this proposed simple keymanager API, so it's unclear how soon this option would materialize:

- Prysm: :hourglass_flowing_sand: Interested in following this standard once there's bandwidth
- Lighthouse: :hourglass_flowing_sand: Might follow the API, however it conflicts with the current implemented backend
- Teku: :interrobang: No signal
- Nimbus: :hourglass_flowing_sand: Might be interested in implementing the backed
- Lodestar: :x: Not actively pursuing this

**C: Use a remote signer with a UI attached**

Connect a validator client of some implementation to a unique remote signer that has a UI for key managment. This solution would allow a safe way to switching between clients. However remote signer support is not universal

- Prysm: :hourglass_flowing_sand: Pending implementation, high priority item
- Lighthouse: :hourglass_flowing_sand: developed and merged to unstable, to be released soon https://github.com/sigp/lighthouse/pull/2522
- Teku: :heavy_check_mark: Supports
- Nimbus: :hourglass_flowing_sand: Not yet, requested https://github.com/status-im/nimbus-eth2/issues/2948
- Lodestar: :hourglass_flowing_sand: To be implemented soon (in pipeline)

EIP-3030: BLS Remote Signer HTTP API https://eips.ethereum.org/EIPS/eip-3030 wants to standardize the remote signer API, such that any validator client can connect to it. However the current situation is that remote signer clients are not standardized, so interop might not be possible yet. It's unclear if all clients are gonna support Altair in time for their remote signers.

Regarding remote signers, this implementation by Teku is actively used in production and uses a slashing protection db :+1: https://github.com/ConsenSys/web3signer/. However, it requires a CLI for managing keys and slashing protection data, so again missing a UI here. Note it also requires a PostgreSQL instance.

**D: Use Prysm validator client with other beacon nodes**

The Prysm validator client is the only eth2 keymanager implementation with UI support. Given that the beacon node does most of the work and poses the highest risk of consensus failure, users running a Prysm validator client + a non-Prysm beacon node would still contribute significantly to the network client diversity.

The eth2 API for validator client -> beacon node interactions is standardized in https://github.com/ethereum/eth2.0-APIs but Prysm has just started to follow it. We should test the matrix of compatibility between clients to study how feasible this option is:

- Prysm vc + Lighthouse: :x: Prysm won't support eth2 standard API in the VC till the merge
- Prysm vc + Teku: :x: Prysm won't support eth2 standard API in the VC till the merge
- Prysm vc + Nimbus: :x: Prysm won't support eth2 standard API in the VC till the merge
- Prysm vc + Lodestar: :x: Prysm won't support eth2 standard API in the VC till the merge

**Comment by dapplion** [comment]
To explore **D: Use Prysm validator client with other beacon nodes**:

1. Run one beacon node (Lighthouse or Teku or Nimbus) in a sufficiently powerful machine (4-8GB or RAM). You may use docker-compose with their distributed builds.
2. Run one Prysm validator with their v2 release (currently in beta).
3. Connect the Prysm validator to the (1) node API.
4. Monitor logs and performance to ensure all is good.

**Comment by joaquim-verges** [comment]
I'm willing to lend a hand on this, opened an issue on the web3signer repo to discuss about option C: https://github.com/ConsenSys/web3signer/issues/439 - there's a couple of open questions, would love some eyes on it!

**Comment by Pol-Lanski** [comment]
Update on the situation:

From @dapplion 's original posts, there are 2 solutions that are developing nicely: 
**B: Add only UI backend to the client** 
and 
**C: Use a remote signer with a UI attached**

I'm going to slightly rename them since the scope has shifted and is now better defined.

### B) Enable all validator clients to connect to a UI
DAppLion's [initial API proposal](https://github.com/ethereum/beacon-APIs/pull/151) has been reviewed and discussed by all teams and it now has its own repo: https://github.com/ethereum/keymanager-APIs

This would allow us to have a generic UI that connects to any client that implements the standard. 

😀 At least Teku and Lightnouse are implementing it, which means that they could be offered as options in DAppNode. 
😔 No generic UI yet

### C) Use remote signer with a UI attached

😀 Thanks to @joaquim-verges , the standard is being implemented in the web3signer as per: https://github.com/ConsenSys/web3signer/issues/439
😔 No generic UI yet

## Work on DAppNode's side
Regardless of which option, B or C, becomes available first, there's 3 things that need to happen in parallel. 

1️⃣ Users in DAppNode are currently using Prysm. To migrate to any other solution, they will need to extract: 1) Validator keys, 2) Slashing protection data from the current Prysm client.

2️⃣ When more validator packages become available, there is a chance that if the user does not follow a particular sequence of steps, two validators might be running and due to some bug, two validate with the same key. We must mitigate this by avoiding two validator packages to run at the same time. This is being addressed here: https://github.com/dappnode/DNP_DAPPMANAGER/issues/913

3️⃣ Whether it's for a validator client that does not have a UI (all of them except for Prysm) or for the web3signer, a UI that utilizes the [keymanagerAPI](https://github.com/ethereum/keymanager-APIs) needs to be done. We, DAppNode, would prefer NOT to touch this and are looking for someone that can develop it.

**Comment by alexpeterson91** [comment]
Resolved!
