### ISSUE TITLE
mdns  on lightning-network.dappnode  do not work

### ISSUE THREAD

**Issue by kalashnikov2** [dappnode/DAppNode#357]
**Describe the bug**
i enable the Lightning Network Package,  but the domain propagation mdns lightning-network.dappnode does not work  .

the mdns domain  lightning-network.dappnode never its generated/propagated by  dappnode setup

**To Reproduce**
-internet managed by openwrt router
-the mdns domain http://dappnode.local   works

1-install dapp node using ISO
2-instal BTC ETH XMR full nodes
3-install LND
4- the mdns domain lightning-network.dappnode never it's send through the network.

error on firefox  ,  DNS_PROBE_FINISHED_NXDOMAIN

**Expected behavior**

be able to open the LND web interface 

**Screenshots**

![imagen](https://user-images.githubusercontent.com/44566/131722683-f4525101-0807-48fb-b115-8cc5fd1b02a4.png)
using a physical tap and wireshark, i never see the mdns of lightning-network.dappnode

**DAppNode version:**

on  nuc  i5 
32gb ram - 2tb ssd
install method  ISO

Core DAppNode Packages versions

    bind.dnp.dappnode.eth: 0.2.6
    dappmanager.dnp.dappnode.eth: 0.2.42, branch: v0.2.43, commit: ec541936
    https.dnp.dappnode.eth: 0.1.1
    ipfs.dnp.dappnode.eth: 0.2.14
    wifi.dnp.dappnode.eth: 0.2.7
    wireguard.dnp.dappnode.eth: 0.1.0

System info

    dockerComposeVersion: 1.25.5
    dockerServerVersion: 20.10.6
    dockerCliVersion: 20.10.6
    os: debian
    versionCodename: bullseye
    architecture: amd64
    kernel: 5.10.0-8-amd64
    Disk usage: 56%

**Additional context**

**Comment by 3alpha** [comment]
Only `dappnode.local` is supposed to be resolved by mDNS. Any other domain is resolved by `bind.dnp.dappnode.eth` DNS server which means you have to be connected either to the DAppNode's Wifi or VPN.

We decided to opt out of `.dappnode` TLD to be resolved via mDNS because default linux config in `/etc/nsswitch.conf` is with `mdns4_minimal` and that won't work. Additionally, resolution of `\w+.dappnode.local` domains was proven to be unreliable across different machines/OS. That is, among other things, why only `dappnode.local` works.
