### ISSUE TITLE
Switch WiFi to client mode

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DAppNode#499]
Feature request

I'd like to have the ability to use wifi as a backup for when internet is unavailable on the Ethernet connection

Within the dappnode UI, under wifi. I'd like to be able to switch the mode to make dappnode function as a normal wifi client. 

This would help if my internet connection is down and I temporarily need to require dappnode to connect to the internet through my 5G phone hotspot.

**Comment by alexpeterson91** [comment]
Wi-Fi connections are too unstable for dappnodes and if you're planning on using a cell hotspot that's going to be even less reliable even if it was connected via USB. It's possible as is to configure the Wi-Fi to be the internet source several users have done this over the years but it's proven to, as expected, not be reliable enough to run Dappnode so this isn't something the team is gonna be spending any time on. technically it's something we could support, but in reality we can't because it's not something that would work especially with this use case. When we sell NUCs with WiFi 6E (6Ghz band). And everyone has Wi-Fi 6E home networks it's possible that may be more stable and a Wi-Fi connection may actually be stable enough to use as the internet source. But an LTE Wi-Fi hotspot is not gonna cut it ever. (I do have a couple NUCs with Wi-Fi 6E and my home is all WiFi 6E so if I have time it's something I could test but it'd be purely PoC since Wi-Fi 6E is far from ubiquitous right now.)

**Comment by CMTRACE** [comment]
Wifi is totally fine to have as a stable connection, it’s widely used in enterprise. So not sure why you’d asset it’s unstable

At aside, as a temporary measure of the internet connection is out it’s inherently more reliable if the Ethernet connection is out so again strange to assert its less reliable. But ok.
________________________________
