### ISSUE TITLE
(Yet) Another way to access DAppNode

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DAppNode#514]
**Introduction**

General consensus seems to be that accessing DAppNode on local network is not as simple as it can be. Current approach is guided by security concerns and technical constraints.

**New way to access**

There are few thing we need to do to make this work
 - HTTP server running inside DAppNode can be leveraged as a proxy server with few tweaks
 - DNS :weary:
 Main blocker in the all this is DNS. What needs to be added is (yet) another DNS server, which would resolve every `.dappnode` domain to local IP of the DAppNode machine.
- DNS :weary:
Users machine would need to be configured to actually use this new DNS server. That can be done either manually, or changing router's DHCP server settings

I have PoC running on my DAppNode. I edited DNP_HTTPS configuration to allow traffic from my network, I added dnscrypt-proxy server to my machine and manually edited DNS entry in my network settings. It works, however it needs lot more work if we were to ship this.

**Conclusion**

This can be done but it is not user friendly as it should be. Moreover, it introduces a big hole in DAppNode's isolated sandbox which can pose significant security concerns. We should weigh these carefully before deciding on moving forward with this.

**Comment by alexpeterson91** [comment]
My opinion is that the local proxy has been too buggy for me to use since day 1.  It definitely opens a huge hole security wise. I don't think we push VPN usage enough. Most new users ignore the VPN until it's too late. When the VPN should be the only way you connect after initial setup. Obviously an overhaul could help it but if it makes it less user friendly than it is now I vote no. Especially with security concerns. We don't wanna strip away any other layers of security and probably should add back some. The fact that users can't access the .dappnode domains vis local proxy I think is a good thing it keeps them from continuing to use what's essentially just an initial setup convenience feature.

**Comment by 3alpha** [comment]
Yeah, local proxy has its own issues, all of which are connected with how mDNS resolution works. That's why my plans to expand its features were nonstarter. This approach is bit different and mitigates those completely, but requires users to mess with their router settings. I have it working pretty well on my testing setup, no issue whatsoever.

Security-wise, I mostly agree, only way I would be okay with doing it with big red disclaimer button. Maybe solution could be allowing this on package-by-package basis. I think this is a good discussion to have.

**Comment by tjayrush** [comment]
I am a total outsider, so I'm sure I don't know all the considerations you're struggling with. That might be a good thing or a bad thing, but...

What I want is very simple: allow me to take this computer out of its box, plug it into my network, and with ZERO configuration, allow me to access the RPC. Just like every other computer I've owned since 1994.

You can have a section in the packaging that says, "If you want a super-secure system, do this..." but forcing regular humans to go through anything related to the configuration is a mistake.

The system is already 10 times more secure for your users simply by bringing it in-house. Plus, if the user's internal systems are compromised, how is securing the router going to matter?

Should the dAppNode be accessible to the external internet by default? Obviously no. But should it appear exactly like any other computer on the network internally? I think obviously yes.

Just my $0.02 and as I say, I'm a total outsider, so ignore this if you like.

**Comment by 3alpha** [comment]
Hey, thanks for the feedback. We really appreciate it. There are many consideration that have to be done while implementing feature and every feedback helps. 

For example, maybe it would be okay if we were to have some option in wizard to expose RPC by default using similar mechanism as this one. I guess that is the biggest painpoint, because day to day people are just interested in having their Metamask conencted to their node.

**Comment by CMTRACE** [comment]
I'm definitely on the side of more secure. If people are going to be throwing 32 ETH into this thing as a minimum, security is almost nonnegotiable.

VPN comes unstuck with things like CGNAT obviously and that's a problem not with DN but with the users choice in ISP. Often times it's a simple phone call to resolve.

I'm strongly in favour of extreme security at all levels as default. If people want a question added to the out of box experience that allows a "YOLO mode" with direct access then sure thing. But it should be reversible and absolutely not the default setting.

Hell, I'd love some kind of 2FA on local logon and something like secure boot and bitlocker keys stored in the TPM as they have in windows these days.

**Comment by 3alpha** [comment]
I am 100% with you. It is out of the question that it would be default beahviour. 

What we need to consder is that not everybody will be staking and this layer of security is just annoying. What I am most scared of is scenario where people  click YOLO button, stuff happens and then it becomes DAppNode issue. Can't respond to that as DAppNode team member with "kek rekt". But in the other hand I am big proponent of letting people to do what they want. 

That is why I opened this issue to see where we, as community, stand on this.

**Comment by CMTRACE** [comment]
Totally understand. In my day job I manage large enterprise and honestly dappnode is in a wonderful spot as a walled garden to implement the gold standard security measures as default.

I'd only suggest if and when people decide to disregard the standard that this decision is logged, displayed in the system
Health summary and can be collected in support data when required. 

The community would benefit greatly when someone deviates from the standard and runs into trouble. As inevitably they will complain they were unaware or it's not their fault. It would be in the community best interest to be able to see clearly where it went wrong.

Building out a diagnostics tab with live issues on the system and checks for cgnat etc would be a great starting point for the community to offer assistance while filtering out the myriad of complexities in home networking setups.

Allowing dappnode to connect to a wifi network would also help isolating issues to a home network if, for instance, dappnode works on a friends wifi or phone hotspot but not at home.

**Comment by JHGrove3** [comment]
Too many people are not making use of the WiFi access.  In fact, I think a lot of them are disabling WiFi (sometimes at the BIOS level) because a security checklist tells them to.

But for Dappnode, the WiFi access provides an important backup way for users to access their dashboard if something goes wrong with the VPN.
