### ISSUE TITLE
Develop tests for the installer to be run on a Github self-host runner

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#526]
Develop tests for the installer. Take into account that the tests will be run on a **real dappnode environment**.

Tests to develop:
- Script tests
  - Install pre-rrequisites
  - Install dappnode
  - Uninstall dappnode
- ISO tests:
  - Setup: use virtualbox api to set-up the environment
  - Install Dappnode ISO in virtual box

**Comment by dsimog01** [comment]
For ISO testing, we could have a self-hosted runner connected to GitHub that performs SSH connection to another device (a NUC) which will generate the new ISO. This ISO will be burnt in a USB device that will be connected to the NUC and a `reboot` will be executed to trigger the installation. After some minutes, the first device will be able to reboot the second one and, then, it will connect via SSH again to test the installation.

**Comment by dsimog01** [comment]
If we want to test both the ISO and the script installation in the same device, we could have 2 USB drives connected to the NUC and keep one of them with some unattended version of Ubuntu or Debian if possible, so that this becomes the default state for the NUC before performing the script installation.
