### ISSUE TITLE
Network auto configration failed

### ISSUE THREAD

**Issue by f1lander** [dappnode/DAppNode#539]
**Describe the bug**

I'm trying to install dappnodeOs, clean install, but I got a network config failed error when starting the process, is this because my pc does not have the LAN connection yet? can I config a wifi connection?

**Screenshots**

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/5679878/215173928-2fd76ee1-d290-4409-881d-89d2336958a5.png">

**Comment by alexpeterson91** [comment]
Must be hard wired into your router or switch permanently. For real stability. It's possible to use Wi-Fi and some people have configured to do so but have lots of errors. We don't support this as configuration and can't support it since we've seen too many issues with every user who's tried to use WiFi. You need to do a reinstall with the internet connected via Ethernet to your network router or switch to for the installation to work properly. 
Community members may be able to help on discord or the forum but not on GitHub. As we do not officially support it and don't have time to dedicate to it until Wi-Fi is far more reliable like with Wi-Fi 6E or 7 is widespread and ubiquitous on all models we sell and it's the standard most users have as their home routers/access points.

**Comment by f1lander** [comment]
> Must be hard wired into your router or switch permanently. For real stability. It's possible to use Wi-Fi and some people have configured to do so but have lots of errors. We don't support this as configuration and can't support it since we've seen too many issues with every user who's tried to use WiFi. You need to do a reinstall with the internet connected via Ethernet to your network router or switch to for the installation to work properly. 
> Community members may be able to help on discord or the forum but not on GitHub. As we do not officially support it and don't have time to dedicate to it until Wi-Fi is far more reliable like with Wi-Fi 6E or 7 is widespread and ubiquitous on all models we sell and it's the standard most users have as their home routers/access points. 

Thanks, I did it with wired connection
