### ISSUE TITLE
Unable to create ISO using docker

### ISSUE THREAD

**Issue by clamdad** [dappnode/DAppNode#542]
Creating an ISO using docker fails.

**To Reproduce**

Follow the instructions in the README:

1. git clone https://github.com/dappnode/DAppNode.git
2. `cd DAppNode`
3. `docker-compose build` (completes without error)
4. `docker-compose up`
5.Error--> `generate_ISO.sh` not found

**Expected behavior**

Expected an ISO to be created in the images subfolder.

**Screenshots**

```
PS C:\work\git\dappnode\DAppNode> docker-compose up
docker-compose : Creating network "dappnode_default" with the default driver
At line:1 char:1
+ docker-compose up
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Creating networ... default driver:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Creating dappnode_dappnode_installer_1 ... 
Creating dappnode_dappnode_installer_1 ... done
Attaching to dappnode_dappnode_installer_1
[36mdappnode_installer_1  |[0m /usr/local/bin/docker-entrypoint.sh: exec: line 61: /usr/src/app/iso/scripts/generate_ISO.sh: not found
Windows named pipe error: The pipe has been ended. (code: 109)

```

**DAppNode version:**

- Package version: Master branch
- OS: Windows
- Docker version 20.10.22, build 3a2c30b

**Additional context**

**Comment by alexpeterson91** [comment]
Sorry the readme file is out of date by a while I think I'll take a look at it when I have some time and get it updated I think it's been on the back burner for a while since refactoring the installer has been a priority of the team's for a while now but more important things keep popping up. I'll check in on that too.  

Anyways every time I've ever generated my own ISOs, I run `docker-compose up` in the ISO directory. And it always works. ISO is generated in the images directory. 
I do a lot of experimental ISOs custom Configs. Testing new versions for new hardware with new required drivers etc.

**Comment by clamdad** [comment]
Thank you, sir.  I spun up an Ubuntu VM, and the README instructions worked perfectly there with no issues.
So it only seems to be an issue with windows.

The good news is the new ISO I created worked very well.  I needed a new one because I had some issues with the publicly downloadable one at https://iso.dappnode.io/, which seems to be 6 months old or so.

**Comment by alexpeterson91** [comment]
AFAIK the iso.dappnode.io link stopped getting updated a while ago. You can generally find the latest releases in the releases folder of this repo. Most recent posted [here](https://github.com/dappnode/DAppNode/releases/tag/v0.2.64) is from December and there's been core updates since then but only 2 published and one was a hotfix.
 @pablomendezroyo can you make sure we have the latest ISOs posted and marked as latest release?  @eduadiez can you please update the subdomain at `iso.dappnode.io`? I've had several users report that the iso is very outdated. It's hosting the v0.2.56 AMD64 attended iso, which is obviously way out of date. As of writing this comment the latest posted iso on GH in this repo is v0.2.64. But aren't we on v0.2.66 currently

**Comment by pablomendezroyo** [comment]
I have updated the ISO latests. However we must check that the docs point to the latest release in Github
