### ISSUE TITLE
dappnode_wireguard: command not found

### ISSUE THREAD

**Issue by dreadedhamish** [dappnode/DAppNode#558]
Fresh install on Ubuntu 22.10 (desktop) within Virtualbox (latest) using the scripts, firstly I experienced the 403 Forbidden error when trying to access the node locally. I then tried to follow the instructions for connecting via VPN using the command line as I couldn't access local or wifi ( https://docs.dappnode.io/user/guides/access/vpn#setting-up-a-vpn-client-from-the-dappnode-terminal), and the command "dappnode_wireguard" gives the error "Command not found".

Any suggestions?

**Comment by pablomendezroyo** [comment]
Hey! looks like you are facing this issue https://github.com/dappnode/DAppNode/issues/371

Run `source /usr/src/dappnode/DNCORE/.dappnode_profile`

**Comment by dsimog01** [comment]
Hey @dreadedhamish! In general it does not make sense to install dappnode inside a machine that is not dedicated specifically for it. I recommend you try to install it via script or ISO and you use another device to access to the UI of your dappnode. However, you might need to reboot in order to be able to run commands like `dappnode_help`. I am closing this issue as it looks like there is no bug, you can contact via support channel in our Discord for further questions!

**Comment by dreadedhamish** [comment]
I'm doing development, and don't have a spare machine to dedicate to this process.  I followed the instructions exactly for both errors I encountered - so there are bugs somewhere.
