### ISSUE TITLE
ISO image does not serve UI on LAN

### ISSUE THREAD

**Issue by stoooops** [dappnode/DAppNode#574]
I would prefer to just have the port in the documentation and I can connect directly via IP. That's how everything else on my LAN works.

![image](https://github.com/dappnode/DAppNode/assets/3518037/938c3355-2722-480c-bb93-bb985cc1fe94)

**Comment by alexpeterson91** [comment]
Thank you for editing your post, we do not tolerate the kind of speech used in your previous versions of this post.  
As to your question, there is no way to access your dappnode as you describe, it's part of the security model and architecture.  
The recommended way to access your dappnode fully is using Wireguard the VPN, it is the safest way to connect, you cannot connect to an IP and port of your dappnode via local network there are none open for access to any of the UIs for security reasons, because all the packages, software, UIs and everything is located on an internal Docker network on the dappnode complete with a full DNS resolver within the Docker network to access packages using DNS names.  In order to control or access anything you must have access to this internal network, it's one of the major security layers protecting your dappnode from unauthorized access.  To join this internal docker network you must connect to your dappnode via VPN, Wireguard preferred, or your Dappnode's Wifi hotspot (if equipped).  
You are trying to access the local proxy, which is a feature that has always been very buggy, it was introduced as a convenience method for one time setup before you start to use VPNs to connect, which allows full secure access to your Dappnode from anywhere.  
This screenshot shared is showing the bug that wont allow you to connect to your dappnode using the local proxy, even if you could connect (its all dependent on your network and what else is on your network, along with a bit of luck if the local proxy will work at all, im a Core team member and its worked 3 times for me ever, i have 6 dappnodes and have been doing this for 3 years.) even if it did connect you wouldnt be able to access any UIs or around half or more of packages, since the local proxy `http://dappnode.local` doesn't have access to any of those even if `dappnode.local` does resolve and get you to the main AdminUI/DAPPManager, it cant access any other UIs only the management UI, since it's only a convenience feature for initial setup.

Please check our [documentation](https://docs.dappnode.io/user/guides/access/) for information on how to connect using methods other than the local network proxy, which will not work for you given the information you've shared.

**Comment by alexpeterson91** [comment]
If you have any further questions please contact us on our [Discord](https://discord.com/servers/dappnode-747647430450741309), we have a very welcoming community with hundreds of users online at any given time happy to give support for Dappnode users, especially for initial setup.
