### ISSUE TITLE
Be able to map non-mapped port

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#79]
Display a `plus` icon to add a new mapping. A use case would be to expose the JSON RPC of a node, which is not natively mapped to any host's port
![addp.jpg](https://images.zenhubusercontent.com/5affea5c4b5806bc2bd3cb7e/b05713a1-983f-4521-9971-f617621f0aa8)

**Comment by dapplion** [comment]
Use case: a user activates the Ethchain WebSocket and wants to map it to some port.

**Comment by dapplion** [comment]
### DAPPMANAGER:
- [ ] RPC call `changePortMappings`. It should accept a portMappings array and merge it with the existing mappings, detecting and applying overwrites.

```js
async function changePortMappings({ id, portMappings })

portMappings = [
  { host: "30404", container: "30303", type: "UPD" }
]
```

### ADMIN
- [ ] In the config view add a `ports` section to change or add port mappings.

**Comment by lodotek** [comment]
I see this was close but without a linked PR or commit. What happened with this?
I am trying to track down the issue with duplicated port mappings in the UI and the inability to add mappings due to a UI issue.

Also reported here: https://discord.com/channels/747647430450741309/747816600077598730/929515609295814716

**Comment by dapplion** [comment]
@pablomendezroyo can you take a look?
