### ISSUE TITLE
Security issue: dapp node link provided by QR code uses insecure connection

### ISSUE THREAD

**Issue by uniconstructor** [dappnode/DAppNode#95]
Steps to reproduce
1) Scan QR code with phone
2) Open resulting URL via browser

Result: http protocol used to connect http://otp.dappnode.io
Site supports https but don't do redirection automatically

More then that - even my browser (Brave) that should automatically redirect me from unsecure url to secure don't do anything.

Now I have to reset my credentials because it's compromised.

Please change generated link to credentials from http to https and set up automatic https redirection for otp.dappnode.io domain.

**Comment by uniconstructor** [comment]
![IMG_20190429_113129](https://user-images.githubusercontent.com/1384545/56884456-86174a00-6a72-11e9-8888-f2d810c71ede.jpg)

**Comment by uniconstructor** [comment]
(screen with proof)

**Comment by dapplion** [comment]
@uniconstructor Thanks for opening an issue for this. The credentials you obtained (for DAppNode v0.1.x version) are contained in the hash part of the URL. So they are never sent over the network regardless of the protocol. However, someone could do a man in the middle attack and replace the OTP web with a malicious version that forwards the credentials somewhere else.

Since your message, we have upgraded to version 0.2.x. Now the VPN link points to the DAppNode's IP which serves a site to decrypt the credentials on the web. Since there isn't an easy way to get certificates for each DAppNode's IP the connection is HTTP (insecure).

We do not have a solution for this vulnerability ATM. Any ideas or suggestions on how to tackle this issue are super appreciated <3

**Comment by vdo** [comment]
Adding SSL is problematic for many reasons:

- There's no way to have trusted SSL certificates for our internal .eth  and .dappnode domains.
- Using Let's Encrypt makes use of a centralized service, only works for public registered domains, and they need to be renewed periodiacally.
- Self-signed certificates need to be generated for each DAppNode, and since they are not trusted by browsers, they don't provide CSRF protection anyway.

We are still trying to figure out the best approach to solve this, but as @dapplion said, any recommendation is very welcome!

**Comment by dapplion** [comment]
@vdo Would it make sense to allow the DAppNode admin to turn on an option in the UI to generate self-signed certificates? If that specific DAppNode's user trusts the certificate and are not annoyed by the first massive warning browsers show, would that provide a quick fix advantage for people really concerned with security?

**Comment by vdo** [comment]
But what are we fixing with it? Again, the ADMIN UI is protected by the VPN anyway, and a self signed certificate would not protect against CSRF if the user has to accept it.

**Comment by dapplion** [comment]
Closing as this procedure to obtain VPN credentials is not used anymore
